#!/bin/zsh

alias ll="ls -lhFG"
alias la="ls -lahFG"
alias cleardns="sudo killall -HUP mDNSResponder;sudo killall mDNSResponderHelper;sudo dscacheutil -flushcache"

alias weather="curl https://wttr.in/riga\?FQ"

alias bubu="brew update && brew upgrade && brew cleanup"
