# version: 1.0.0
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
continuation_prompt = "[λ ](dimmed green)"
format = "$sudo$directory$git_branch$git_status$fill$deno$nodejs$cmd_duration$battery$time\n$character"


[fill]
symbol = ' '


[character]
format = "$symbol "
success_symbol = "[λ](bright-green)"
error_symbol = "[✗](red)"


[sudo]
format = "[$symbol]($style)"
style = "bold italic bright-purple"
symbol = "⚡"
disabled = false


[directory]
style = "blue"
truncation_length = 0
truncate_to_repo = false
use_os_path_sep = true
read_only = "readonly "
read_only_style = "bold red"
before_repo_root_style = "blue"
repo_root_style = "yellow"
format = "[$read_only]($read_only_style)[$path]($style) "
repo_root_format = "[$read_only]($read_only_style)[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style) "
#format = '[[$path]($read_only_style)]($read_only_style) '


[cmd_duration]
disabled = false
style = "yellow"
format = "[$duration]($style) "
show_milliseconds = true
min_time=500


[time]
disabled = false
style = "dimmed white"
format = "[$time]($style)"
time_format = "%T"
utc_time_offset = "local"


[battery]
format = "[$percentage $symbol]($style)"
full_symbol = "󰁹"
charging_symbol = "[󰂄](italic bold green)"
discharging_symbol = "󰁽"
unknown_symbol = "󰂃"
empty_symbol = "󰂎"


[[battery.display]]
threshold = 20
style = "italic bold red"


[[battery.display]]
threshold = 60
style = "italic dimmed bright-purple"


[[battery.display]]
threshold = 70
style = "italic dimmed yellow"


[git_branch]
symbol = ""
style = "bright-black"
format = "[$symbol$branch(:$remote_branch)]($style) "


[git_status]
style = "bright-red"
format = "[$all_status$ahead_behind]($style) "
ignore_submodules = true
conflicted = '!'
untracked = "?"
stashed = "\\$"
modified = "*"
staged = "+"
renamed = "->"
deleted = "✗"
ahead = "↑"
behind = "↓"


[deno]
format = " [deno](italic) [∫ $version](green bold)"
version_format = "${raw}"


[nodejs]
style = "dimmed green"
symbol = ""
format = "[$version]($style) "
detect_files = ["package.json", "package-lock.json", "yarn.lock"]
detect_folders = ["node_modules"]
detect_extensions = []
