#!/bin/zsh

# Update App Store apps
sudo softwareupdate -i -a

# Update Homebrew (Cask) & packages
brew update
brew upgrade

# Update npm & packages
npm install npm -g
npm update -g

# Update Ruby & gems - do i need dis?..
#sudo gem update —system
#sudo gem update
